### ISSUE TITLE
link to fluentd-daemonset-papertrail.yaml is broken

### ISSUE THREAD

**Issue by engintekin** [solarwinds/fluentd-deployment#4]
in the docs fluentd-daemonset-papertrail.yaml link is broken as the yaml file is transferred to this repo from https://github.com/solarwinds/fluent-plugin-papertrail.

https://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-kubernetes/#log-from-all-containers-and-systems

**Comment by johlym** [comment]
Hey @engintekin We just pushed out a fix for this. Thanks for pointing that out!
